# -*- coding: utf-8 -*-
"""Nobel_Prize_Analysis_(start).ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/17YBxJgEbyv-AShX5Ol0kytnxWE9y6HUo

# Setup and Context

### Introduction

On November 27, 1895, Alfred Nobel signed his last will in Paris. When it was opened after his death, the will caused a lot of controversy, as Nobel had left much of his wealth for the establishment of a prize.

Alfred Nobel dictates that his entire remaining estate should be used to endow “prizes to those who, during the preceding year, have conferred the greatest benefit to humankind”.

Every year the Nobel Prize is given to scientists and scholars in the categories chemistry, literature, physics, physiology or medicine, economics, and peace.

<img src=https://i.imgur.com/36pCx5Q.jpg>

Let's see what patterns we can find in the data of the past Nobel laureates. What can we learn about the Nobel prize and our world more generally?

### Upgrade plotly (only Google Colab Notebook)

Google Colab may not be running the latest version of plotly. If you're working in Google Colab, uncomment the line below, run the cell, and restart your notebook server.
"""

# Commented out IPython magic to ensure Python compatibility.
# %pip install --upgrade plotly

"""### Import Statements"""

import pandas as pd
import numpy as np
import plotly.express as px
import seaborn as sns
import matplotlib.pyplot as plt

"""### Notebook Presentation"""

pd.options.display.float_format = '{:,.2f}'.format

"""### Read the Data"""

df_data = pd.read_csv('nobel_prize_data.csv')

"""Caveats: The exact birth dates for Michael Houghton, Venkatraman Ramakrishnan, and Nadia Murad are unknown. I've substituted them with mid-year estimate of July 2nd.

# Data Exploration & Cleaning

**Challenge**: Preliminary data exploration.
* What is the shape of `df_data`? How many rows and columns?
* What are the column names?
* In which year was the Nobel prize first awarded?
* Which year is the latest year included in the dataset?
"""

df_data.describe
df_data.dtypes

df_data.sort_values("year",ascending= True)
df_data[df_data.birth_country == "Cuba"]

"""**Challange**:
* Are there any duplicate values in the dataset?
* Are there NaN values in the dataset?
* Which columns tend to have NaN values?
* How many NaN values are there per column?
* Why do these columns have NaN values?

### Check for Duplicates
"""

df_data.duplicated().any()

"""### Check for NaN Values"""

df_data.isna().sum()

col_subset = ['year','category', 'laureate_type',
              'birth_date','full_name', 'organization_name']
df_data.loc[df_data.birth_date.isna()][col_subset]

"""### Type Conversions

**Challenge**:
* Convert the `birth_date` column to Pandas `Datetime` objects
* Add a Column called `share_pct` which has the laureates' share as a percentage in the form of a floating-point number.

#### Convert Year and Birth Date to Datetime
"""

df_data.birth_date = pd.to_datetime(df_data.birth_date)
df_data.prize_share

"""#### Add a Column with the Prize Share as a Percentage"""

separated_values = df_data.prize_share.str.split('/', expand=True)
numerator = pd.to_numeric(separated_values[0])
denomenator = pd.to_numeric(separated_values[1])
df_data['share_pct'] = numerator / denomenator

df_data.groupby("year").count()

"""Own Questions:

1. What is the average age that the prize was won?
2. What is the top 5 counties with most Nobels?
3. Which organization won the most prizes?  
"""

df_data["year_born"] = pd.DatetimeIndex(df_data.birth_date).year
df_data["age"] = df_data.year - df_data.year_born
df_data.age.describe()

df_data.groupby("birth_country").agg({"prize": "count", "age": "mean"}).sort_values("prize", ascending = False)

df_data.groupby("organization_name").agg({"prize": "count"}).sort_values("prize", ascending = False)

"""# Plotly Donut Chart: Percentage of Male vs. Female Laureates

**Challenge**: Create a [donut chart using plotly](https://plotly.com/python/pie-charts/) which shows how many prizes went to men compared to how many prizes went to women. What percentage of all the prizes went to women?
"""

biology = df_data.sex.value_counts()
biology

fig = px.pie(labels=biology.index,
             values=biology.values,
             title="Percentage of Male vs. Female Winners",
             names=biology.index,
             hole=0.4,)

fig.update_traces(textposition='inside', textfont_size=15, textinfo='percent')

fig.show()

"""# Who were the first 3 Women to Win the Nobel Prize?

**Challenge**:
* What are the names of the first 3 female Nobel laureates?
* What did the win the prize for?
* What do you see in their `birth_country`? Were they part of an organisation?
"""

df_data[df_data.category == "Economics"].sort_values("year", ascending = False)



"""# Find the Repeat Winners

**Challenge**: Did some people get a Nobel Prize more than once? If so, who were they?
"""

df_data.groupby("full_name").agg({"prize": "count"}).sort_values("prize", ascending = False)



"""# Number of Prizes per Category

**Challenge**:
* In how many categories are prizes awarded?
* Create a plotly bar chart with the number of prizes awarded by category.
* Use the color scale called `Aggrnyl` to colour the chart, but don't show a color axis.
* Which category has the most number of prizes awarded?
* Which category has the fewest number of prizes awarded?
"""

prizes_per_category = df_data.category.value_counts()
v_bar = px.bar(
        x = prizes_per_category.index,
        y = prizes_per_category.values,
        color = prizes_per_category.values,
        color_continuous_scale='Aggrnyl',
        title='Number of Prizes Awarded per Category')

v_bar.update_layout(xaxis_title='Nobel Prize Category',
                    coloraxis_showscale=False,
                    yaxis_title='Number of Prizes')
v_bar.show()

"""**Challenge**:
* When was the first prize in the field of Economics awarded?
* Who did the prize go to?
"""

df_data[df_data.category == "Economics"].sort_values("year")

"""# Male and Female Winners by Category

**Challenge**: Create a [plotly bar chart](https://plotly.com/python/bar-charts/) that shows the split between men and women by category.
* Hover over the bar chart. How many prizes went to women in Literature compared to Physics?

<img src=https://i.imgur.com/od8TfOp.png width=650>
"""

sex_per_category = df_data.groupby(["sex", "category"], as_index = False).agg({"prize": "count"}).sort_values("prize", ascending = False)

v_bar = px.bar(
      x = sex_per_category.category,
      y = sex_per_category.prize,
      color = sex_per_category.sex,
      color_continuous_scale='Aggrnyl',
      title='Number of Prizes Awarded per Category (per sex)')

v_bar.update_layout(
    xaxis_title='Nobel Prize Category',
    coloraxis_showscale=False,
    yaxis_title='Number of Prizes'
)

v_bar.show()



"""# Number of Prizes Awarded Over Time

**Challenge**: Are more prizes awarded recently than when the prize was first created? Show the trend in awards visually.
* Count the number of prizes awarded every year.
* Create a 5 year rolling average of the number of prizes (Hint: see previous lessons analysing Google Trends).
* Using Matplotlib superimpose the rolling average on a scatter plot.
* Show a tick mark on the x-axis for every 5 years from 1900 to 2020. (Hint: you'll need to use NumPy).

<img src=https://i.imgur.com/4jqYuWC.png width=650>

* Use the [named colours](https://matplotlib.org/3.1.0/gallery/color/named_colors.html) to draw the data points in `dogerblue` while the rolling average is coloured in `crimson`.

<img src=https://i.imgur.com/u3RlcJn.png width=350>

* Looking at the chart, did the first and second world wars have an impact on the number of prizes being given out?
* What could be the reason for the trend in the chart?

"""

prize_per_year = df_data.groupby("year").agg({"prize": "count"}).sort_values("year", ascending = True)
moving_average = prize_per_year.rolling(window=5).mean()
prize_per_year

plt.figure(figsize=(16,8), dpi=200)
plt.title('Number of Nobel Prizes Awarded per Year', fontsize=18)
plt.yticks(fontsize=14)
plt.xticks(ticks=np.arange(1900, 2021, step=5),
           fontsize=14,
           rotation=45)

ax = plt.gca() # get current axis
ax.set_xlim(1900, 2020)

ax.scatter(x=prize_per_year.index,
           y=prize_per_year.values,
           c='dodgerblue',
           alpha=0.7,
           s=100,)

ax.plot(prize_per_year.index,
        moving_average.values,
        c='crimson',
        linewidth=3,)

plt.show()





"""# Are More Prizes Shared Than Before?

**Challenge**: Investigate if more prizes are shared than before.

* Calculate the average prize share of the winners on a year by year basis.
* Calculate the 5 year rolling average of the percentage share.
* Copy-paste the cell from the chart you created above.
* Modify the code to add a secondary axis to your Matplotlib chart.
* Plot the rolling average of the prize share on this chart.
* See if you can invert the secondary y-axis to make the relationship even more clear.
"""

share_per_year = df_data.groupby("year").agg({"share_pct": "mean"}).sort_values("year", ascending = True)
share_roll = share_per_year.rolling(window=5).mean()

plt.figure(figsize=(16,8), dpi=200)
plt.title('Number of Nobel Prizes Awarded per Year', fontsize=18)
plt.yticks(fontsize=14)
plt.xticks(ticks=np.arange(1900, 2021, step=5),
           fontsize=14,
           rotation=45)

ax = plt.gca() # get current axis
ax2 = plt.twinx()
ax.set_xlim(1900, 2020)

# Can invert axis
ax2.invert_yaxis()

ax.scatter(x=prize_per_year.index,
           y=prize_per_year.values,
           c='dodgerblue',
           alpha=0.7,
           s=100,)

ax.plot(prize_per_year.index,
        moving_average.values,
        c='crimson',
        linewidth=3,
        label = "5Y Moving Average prizes",)

ax2.plot(share_roll.index,
        share_roll.values,
        c='grey',
        linewidth=3,
        label = "5Y Moving Average prize share",)


ax.legend(loc='upper left', fontsize=12)  # Line label for the first axis
ax2.legend(loc='lower right', fontsize=12)  # Line label for the second axis

plt.show()







"""# The Countries with the Most Nobel Prizes

**Challenge**:
* Create a Pandas DataFrame called `top20_countries` that has the two columns. The `prize` column should contain the total number of prizes won.

<img src=https://i.imgur.com/6HM8rfB.png width=350>

* Is it best to use `birth_country`, `birth_country_current` or `organization_country`?
* What are some potential problems when using `birth_country` or any of the others? Which column is the least problematic?
* Then use plotly to create a horizontal bar chart showing the number of prizes won by each country. Here's what you're after:

<img src=https://i.imgur.com/agcJdRS.png width=750>

* What is the ranking for the top 20 countries in terms of the number of prizes?
"""

top20_countries = share_per_year = df_data.groupby("birth_country_current").agg({"prize": "count"}).sort_values("prize", ascending = True)
top20_countries =top20_countries.tail(20)
top20_countries

h_bar = px.bar(x=top20_countries.prize,
               y=top20_countries.index,
               orientation='h',
               color=top20_countries.prize,
               color_continuous_scale='Viridis',
               title='Top 20 Countries by Number of Prizes')

h_bar.update_layout(xaxis_title='Number of Prizes',
                    yaxis_title='Country',
                    coloraxis_showscale=False)



h_bar.show()

"""# Use a Choropleth Map to Show the Number of Prizes Won by Country

* Create this choropleth map using [the plotly documentation](https://plotly.com/python/choropleth-maps/):

<img src=https://i.imgur.com/s4lqYZH.png>

* Experiment with [plotly's available colours](https://plotly.com/python/builtin-colorscales/). I quite like the sequential colour `matter` on this map.

Hint: You'll need to use a 3 letter country code for each country.

"""

df_countries = df_data.groupby(['birth_country_current', 'ISO'],
                               as_index=False).agg({'prize': "count"})

fig = px.choropleth(df_countries, locations="ISO",
                    color="prize", # lifeExp is a column of gapminder
                    hover_name="birth_country_current", # column to add to hover information
                    color_continuous_scale=px.colors.sequential.matter)


fig.update_layout(coloraxis_showscale=True,)

fig.show()







"""# In Which Categories are the Different Countries Winning Prizes?

**Challenge**: See if you can divide up the plotly bar chart you created above to show the which categories made up the total number of prizes. Here's what you're aiming for:

<img src=https://i.imgur.com/iGaIKCL.png>

* In which category are Germany and Japan the weakest compared to the United States?
* In which category does Germany have more prizes than the UK?
* In which categories does France have more prizes than Germany?
* Which category makes up most of Australia's nobel prizes?
* Which category makes up half of the prizes in the Netherlands?
* Does the United States have more prizes in Economics than all of France? What about in Physics or Medicine?


The hard part is preparing the data for this chart!


*Hint*: Take a two-step approach. The first step is grouping the data by country and category. Then you can create a DataFrame that looks something like this:

<img src=https://i.imgur.com/VKjzKa1.png width=450>

"""

df_category = df_data.groupby(['birth_country_current', 'category'],
                               as_index=False).agg({'prize': "count"})


df_category = df_data.groupby(['birth_country_current', 'category'], as_index=False).agg({'prize': 'count'})
merged_df = pd.merge(df_countries, df_category, on='birth_country_current')
merged_df = merged_df.rename(columns={'prize_x': 'total_prize', 'prize_y': 'cat_prize'})
country_totals = merged_df.groupby('birth_country_current')['total_prize'].sum()
top_20_countries = country_totals.nlargest(19).index.tolist()

top_20_df = merged_df[merged_df['birth_country_current'].isin(top_20_countries)]
top_20_df = top_20_df.sort_values('total_prize', ascending=True)
top_20_df

cat_cntry_bar = px.bar(x=top_20_df.cat_prize,
                       y=top_20_df.birth_country_current,
                       color=top_20_df.category,
                       orientation='h',
                       title='Top 20 Countries by Number of Prizes and Category')

cat_cntry_bar.update_layout(xaxis_title='Number of Prizes',
                            yaxis_title='Country')
cat_cntry_bar.show()

df_category = df_data.groupby(['birth_country_current', 'category'],
                               as_index=False).agg({'prize': "count"})
df_category

"""### Number of Prizes Won by Each Country Over Time

* When did the United States eclipse every other country in terms of the number of prizes won?
* Which country or countries were leading previously?
* Calculate the cumulative number of prizes won by each country in every year. Again, use the `birth_country_current` of the winner to calculate this.
* Create a [plotly line chart](https://plotly.com/python/line-charts/) where each country is a coloured line.
"""

prize_per_year = df_data.groupby(["year", "birth_country_current"], as_index=False).agg(
    total_prizes = pd.NamedAgg(column="prize", aggfunc = "count")).sort_values("year")
prize_per_year["cumulative"] = prize_per_year.groupby('birth_country_current')['total_prizes'].cumsum()

# Get the top 10 countries based on the maximum cumulative count of prizes
top_10_countries = prize_per_year.groupby('birth_country_current')['cumulative'].max().nlargest(10).index

# Filter the data to include only the top 10 countries
prize_per_year_top_10 = prize_per_year[prize_per_year['birth_country_current'].isin(top_10_countries)]

prize_per_year_top_10

# Plot the graph with only the top 10 countries
fig = px.line(prize_per_year_top_10, x="year", y="cumulative", color='birth_country_current')

# Add annotations for country names on the right side of the lines
for country in top_10_countries:
    last_value = prize_per_year_top_10[prize_per_year_top_10['birth_country_current'] == country].iloc[-1]
    fig.add_annotation(x=last_value['year'], y=last_value['cumulative'],
                       text=country, showarrow=False,
                       xanchor='left', yanchor='middle', font=dict(color='black', size=10))

# Remove the legend
fig.update_layout(showlegend=False)

# Customize line colors
color_palette = px.colors.qualitative.Plotly[:10]
for i, country in enumerate(top_10_countries):
    fig.update_traces(selector=dict(name=country), line=dict(color=color_palette[i]))

# Add axis labels and a title
fig.update_layout(
    xaxis_title="Year",
    yaxis_title="Cumulative Count of Prizes",
    title="Cumulative Count of Prizes by Country over Time"
)

# Adjust the layout for better readability
fig.update_layout(
    plot_bgcolor='lightgrey',
    margin=dict(t=50, r=50, b=50, l=50),
    font=dict(size=12)
)

# Display the graph
fig.show()

"""# What are the Top Research Organisations?

**Challenge**: Create a bar chart showing the organisations affiliated with the Nobel laureates. It should looks something like this:

<img src=https://i.imgur.com/zZihj2p.png width=600>

* Which organisations make up the top 20?
* How many Nobel prize winners are affiliated with the University of Chicago and Harvard University?
"""

prizes_org = df_data.groupby(["organization_name", "organization_country"], as_index=False).agg(
    total_prizes=pd.NamedAgg(column="prize", aggfunc="count")).sort_values("total_prizes", ascending=False)

prizes_org_top_20 = prizes_org.head(20)

prizes_org_top_20

prizes_org_bar = px.bar(x=prizes_org_top_20.total_prizes,
                       y=prizes_org_top_20.organization_name,
                       color=prizes_org_top_20.organization_country,
                       orientation='h',
                       title='Top 20 Countries by Number of Prizes and Category')

prizes_org_bar.update_layout(xaxis_title='Number of Prizes',
                             yaxis_title='University',
                             yaxis_categoryorder='total ascending')  # Sort y-axis in ascending order

prizes_org_bar.show()

"""# Which Cities Make the Most Discoveries?

Where do major discoveries take place?  

**Challenge**:
* Create another plotly bar chart graphing the top 20 organisation cities of the research institutions associated with a Nobel laureate.
* Where is the number one hotspot for discoveries in the world?
* Which city in Europe has had the most discoveries?
"""

prizes_city = df_data.groupby(["organization_city", "organization_country"], as_index=False).agg(
    total_prizes=pd.NamedAgg(column="prize", aggfunc="count")).sort_values("total_prizes", ascending=False)

prizes_city_top_20 = prizes_city.head(20)
prizes_city_top_20

prizes_city_bar = px.bar(x=prizes_city_top_20.total_prizes,
                       y=prizes_city_top_20.organization_city,
                       color=prizes_city_top_20.organization_country,
                       orientation='h',
                       title='Top 20 Cities by Number of Prizes')

prizes_city_bar.update_layout(xaxis_title='Number of Prizes',
                             yaxis_title='City',
                             yaxis_categoryorder='total ascending')  # Sort y-axis in ascending order

prizes_city_bar.show()

"""# Where are Nobel Laureates Born? Chart the Laureate Birth Cities

**Challenge**:
* Create a plotly bar chart graphing the top 20 birth cities of Nobel laureates.
* Use a named colour scale called `Plasma` for the chart.
* What percentage of the United States prizes came from Nobel laureates born in New York?
* How many Nobel laureates were born in London, Paris and Vienna?
* Out of the top 5 cities, how many are in the United States?

"""

birth_city = df_data.groupby(["birth_city", "birth_country"], as_index=False).agg(
    total_prizes=pd.NamedAgg(column="prize", aggfunc="count")).sort_values("total_prizes", ascending=False)

birth_city_top_20 = birth_city.head(20)
birth_city_top_20

prizes_city_bar = px.bar(x=birth_city_top_20.total_prizes,
                       y=birth_city_top_20.birth_city,
                       color=birth_city_top_20.birth_country,
                       orientation='h',
                       title='Top 20 Birth Cities by Number of Prizes')

prizes_city_bar.update_layout(xaxis_title='Number of Prizes',
                             yaxis_title='City',
                             yaxis_categoryorder='total ascending')  # Sort y-axis in ascending order

prizes_city_bar.show()

"""# Plotly Sunburst Chart: Combine Country, City, and Organisation

**Challenge**:

* Create a DataFrame that groups the number of prizes by organisation.
* Then use the [plotly documentation to create a sunburst chart](https://plotly.com/python/sunburst-charts/)
* Click around in your chart, what do you notice about Germany and France?


Here's what you're aiming for:

<img src=https://i.imgur.com/cemX4m5.png width=300>


"""

prizes_regions = df_data.groupby(["organization_country", "organization_city", "organization_name"], as_index=False).agg(
    total_prizes=pd.NamedAgg(column="prize", aggfunc="count")).sort_values("total_prizes", ascending=False)

prizes_regions

burst = px.sunburst(prizes_regions,
                    path=['organization_country', 'organization_city', 'organization_name'],
                    values='total_prizes',
                    title='Where do Discoveries Take Place?',
                   )

burst.update_layout(xaxis_title='Number of Prizes',
                    yaxis_title='City',
                    coloraxis_showscale=False)

burst.show()

"""# Patterns in the Laureate Age at the Time of the Award

How Old Are the Laureates When the Win the Prize?

**Challenge**: Calculate the age of the laureate in the year of the ceremony and add this as a column called `winning_age` to the `df_data` DataFrame. Hint: you can use [this](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.Series.dt.html) to help you.


"""

df_data.age





"""### Who were the oldest and youngest winners?

**Challenge**:
* What are the names of the youngest and oldest Nobel laureate?
* What did they win the prize for?
* What is the average age of a winner?
* 75% of laureates are younger than what age when they receive the prize?
* Use Seaborn to [create histogram](https://seaborn.pydata.org/generated/seaborn.histplot.html) to visualise the distribution of laureate age at the time of winning. Experiment with the number of `bins` to see how the visualisation changes.
"""

df_data[df_data.age == df_data.age.min()]
df_data[df_data.age == df_data.age.max()]

df_data.age.describe()

"""### Descriptive Statistics for the Laureate Age at Time of Award

* Calculate the descriptive statistics for the age at the time of the award.
* Then visualise the distribution in the form of a histogram using [Seaborn's .histplot() function](https://seaborn.pydata.org/generated/seaborn.histplot.html).
* Experiment with the `bin` size. Try 10, 20, 30, and 50.  
"""

sns.histplot(data=df_data, x="age", bins=10)

"""### Age at Time of Award throughout History

Are Nobel laureates being nominated later in life than before? Have the ages of laureates at the time of the award increased or decreased over time?

**Challenge**

* Use Seaborn to [create a .regplot](https://seaborn.pydata.org/generated/seaborn.regplot.html?highlight=regplot#seaborn.regplot) with a trendline.
* Set the `lowess` parameter to `True` to show a moving average of the linear fit.
* According to the best fit line, how old were Nobel laureates in the years 1900-1940 when they were awarded the prize?
* According to the best fit line, what age would it predict for a Nobel laureate in 2020?

"""

sns.regplot(data=df_data, x="year", y="age", lowess=True)

df_data.sort_values("age")










